/*
 * Sri Lanka HPB Covid-19 Report API
 * API provides the current real time situation of the COVID-19 patients reported in Sri Lanka
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Statistics;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatisticsApi
 */
@Ignore
public class StatisticsApiTest {

    private final StatisticsApi api = new StatisticsApi();

    /**
     * Get current real time situation of the COVID-19 patients reported in Sri Lanka
     *
     * Get current real time situation of the COVID-19 patients reported in Sri Lanka
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiGetCurrentStatisticalGetTest() throws ApiException {
        //Statistics response = api.apiGetCurrentStatisticalGet();
        //System.out.println(response.toString());
        // TODO: test validations

String inputNumber = "0718028640";
        java.text.MessageFormat phoneMsgFmt=new java.text.MessageFormat("{0} {1} {2}");

       /* System.out.println(inputNumber.substring(0,3));
        if(inputNumber.substring(0,3).equals("+94")){
           inputNumber =  inputNumber.replace("+94","0");
        }else if(!inputNumber.substring(0,1).equals("0")){
            inputNumber = "0"+inputNumber;
        }
        //suposing a grouping of 3-3-4
        String[] phoneNumArr={inputNumber.substring(0, 3),
                inputNumber.substring(3,6),
                inputNumber.substring(6)};

        System.out.println(phoneMsgFmt.format(phoneNumArr));*/



        if (inputNumber.substring(0, 1).equals("0")) {
            inputNumber = "94"+inputNumber.substring(1, inputNumber.length());
        }
        System.out.println(inputNumber);

String t = "hello";

String formatStr = "%-"+  (t.length()+1) +"s";
        String temp = String.format(formatStr, "hello")+"World";
        System.out.println(formatStr);
        System.out.println(temp);
    }
}
