/*
 * Sri Lanka HPB Covid-19 Report API
 * API provides the current real time situation of the COVID-19 patients reported in Sri Lanka
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Hospital;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * HospitalData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-22T10:59:48.673Z[GMT]")
public class HospitalData {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("hospital_id")
  private Integer hospitalId = null;

  @SerializedName("cumulative_local")
  private Integer cumulativeLocal = null;

  @SerializedName("cumulative_foreign")
  private Integer cumulativeForeign = null;

  @SerializedName("treatment_local")
  private Integer treatmentLocal = null;

  @SerializedName("treatment_foreign")
  private Integer treatmentForeign = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("updated_at")
  private String updatedAt = null;

  @SerializedName("deleted_at")
  private String deletedAt = null;

  @SerializedName("cumulative_total")
  private Integer cumulativeTotal = null;

  @SerializedName("treatment_total")
  private Integer treatmentTotal = null;

  @SerializedName("hospital")
  private Hospital hospital = null;

  public HospitalData id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "1", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public HospitalData hospitalId(Integer hospitalId) {
    this.hospitalId = hospitalId;
    return this;
  }

   /**
   * Get hospitalId
   * @return hospitalId
  **/
  @Schema(example = "1", description = "")
  public Integer getHospitalId() {
    return hospitalId;
  }

  public void setHospitalId(Integer hospitalId) {
    this.hospitalId = hospitalId;
  }

  public HospitalData cumulativeLocal(Integer cumulativeLocal) {
    this.cumulativeLocal = cumulativeLocal;
    return this;
  }

   /**
   * Get cumulativeLocal
   * @return cumulativeLocal
  **/
  @Schema(example = "1", description = "")
  public Integer getCumulativeLocal() {
    return cumulativeLocal;
  }

  public void setCumulativeLocal(Integer cumulativeLocal) {
    this.cumulativeLocal = cumulativeLocal;
  }

  public HospitalData cumulativeForeign(Integer cumulativeForeign) {
    this.cumulativeForeign = cumulativeForeign;
    return this;
  }

   /**
   * Get cumulativeForeign
   * @return cumulativeForeign
  **/
  @Schema(example = "1", description = "")
  public Integer getCumulativeForeign() {
    return cumulativeForeign;
  }

  public void setCumulativeForeign(Integer cumulativeForeign) {
    this.cumulativeForeign = cumulativeForeign;
  }

  public HospitalData treatmentLocal(Integer treatmentLocal) {
    this.treatmentLocal = treatmentLocal;
    return this;
  }

   /**
   * Get treatmentLocal
   * @return treatmentLocal
  **/
  @Schema(example = "1", description = "")
  public Integer getTreatmentLocal() {
    return treatmentLocal;
  }

  public void setTreatmentLocal(Integer treatmentLocal) {
    this.treatmentLocal = treatmentLocal;
  }

  public HospitalData treatmentForeign(Integer treatmentForeign) {
    this.treatmentForeign = treatmentForeign;
    return this;
  }

   /**
   * Get treatmentForeign
   * @return treatmentForeign
  **/
  @Schema(example = "1", description = "")
  public Integer getTreatmentForeign() {
    return treatmentForeign;
  }

  public void setTreatmentForeign(Integer treatmentForeign) {
    this.treatmentForeign = treatmentForeign;
  }

  public HospitalData createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(example = "2020-03-22 14:10:38", description = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public HospitalData updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(example = "2020-03-22 14:10:38", description = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public HospitalData deletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Get deletedAt
   * @return deletedAt
  **/
  @Schema(example = "2020-03-22 14:10:38", description = "")
  public String getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
  }

  public HospitalData cumulativeTotal(Integer cumulativeTotal) {
    this.cumulativeTotal = cumulativeTotal;
    return this;
  }

   /**
   * Get cumulativeTotal
   * @return cumulativeTotal
  **/
  @Schema(example = "1", description = "")
  public Integer getCumulativeTotal() {
    return cumulativeTotal;
  }

  public void setCumulativeTotal(Integer cumulativeTotal) {
    this.cumulativeTotal = cumulativeTotal;
  }

  public HospitalData treatmentTotal(Integer treatmentTotal) {
    this.treatmentTotal = treatmentTotal;
    return this;
  }

   /**
   * Get treatmentTotal
   * @return treatmentTotal
  **/
  @Schema(example = "1", description = "")
  public Integer getTreatmentTotal() {
    return treatmentTotal;
  }

  public void setTreatmentTotal(Integer treatmentTotal) {
    this.treatmentTotal = treatmentTotal;
  }

  public HospitalData hospital(Hospital hospital) {
    this.hospital = hospital;
    return this;
  }

   /**
   * Get hospital
   * @return hospital
  **/
  @Schema(description = "")
  public Hospital getHospital() {
    return hospital;
  }

  public void setHospital(Hospital hospital) {
    this.hospital = hospital;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HospitalData hospitalData = (HospitalData) o;
    return Objects.equals(this.id, hospitalData.id) &&
        Objects.equals(this.hospitalId, hospitalData.hospitalId) &&
        Objects.equals(this.cumulativeLocal, hospitalData.cumulativeLocal) &&
        Objects.equals(this.cumulativeForeign, hospitalData.cumulativeForeign) &&
        Objects.equals(this.treatmentLocal, hospitalData.treatmentLocal) &&
        Objects.equals(this.treatmentForeign, hospitalData.treatmentForeign) &&
        Objects.equals(this.createdAt, hospitalData.createdAt) &&
        Objects.equals(this.updatedAt, hospitalData.updatedAt) &&
        Objects.equals(this.deletedAt, hospitalData.deletedAt) &&
        Objects.equals(this.cumulativeTotal, hospitalData.cumulativeTotal) &&
        Objects.equals(this.treatmentTotal, hospitalData.treatmentTotal) &&
        Objects.equals(this.hospital, hospitalData.hospital);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hospitalId, cumulativeLocal, cumulativeForeign, treatmentLocal, treatmentForeign, createdAt, updatedAt, deletedAt, cumulativeTotal, treatmentTotal, hospital);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HospitalData {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    hospitalId: ").append(toIndentedString(hospitalId)).append("\n");
    sb.append("    cumulativeLocal: ").append(toIndentedString(cumulativeLocal)).append("\n");
    sb.append("    cumulativeForeign: ").append(toIndentedString(cumulativeForeign)).append("\n");
    sb.append("    treatmentLocal: ").append(toIndentedString(treatmentLocal)).append("\n");
    sb.append("    treatmentForeign: ").append(toIndentedString(treatmentForeign)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    cumulativeTotal: ").append(toIndentedString(cumulativeTotal)).append("\n");
    sb.append("    treatmentTotal: ").append(toIndentedString(treatmentTotal)).append("\n");
    sb.append("    hospital: ").append(toIndentedString(hospital)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
