/*
 * Sri Lanka HPB Covid-19 Report API
 * API provides the current real time situation of the COVID-19 patients reported in Sri Lanka
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Hospital
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-22T10:59:48.673Z[GMT]")
public class Hospital {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("name_si")
  private String nameSi = null;

  @SerializedName("name_ta")
  private String nameTa = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("updated_at")
  private String updatedAt = null;

  @SerializedName("deleted_at")
  private String deletedAt = null;

  public Hospital id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "1", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Hospital name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "National Institute of Infectious Diseases", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Hospital nameSi(String nameSi) {
    this.nameSi = nameSi;
    return this;
  }

   /**
   * Get nameSi
   * @return nameSi
  **/
  @Schema(example = "බෝවන රෝග පිළිබඳ ජාතික ආයතනය", description = "")
  public String getNameSi() {
    return nameSi;
  }

  public void setNameSi(String nameSi) {
    this.nameSi = nameSi;
  }

  public Hospital nameTa(String nameTa) {
    this.nameTa = nameTa;
    return this;
  }

   /**
   * Get nameTa
   * @return nameTa
  **/
  @Schema(example = "தேசிய தொற்று நோயியல் நிறுவனம்", description = "")
  public String getNameTa() {
    return nameTa;
  }

  public void setNameTa(String nameTa) {
    this.nameTa = nameTa;
  }

  public Hospital createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(example = "2020-03-20 01:54:12", description = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public Hospital updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(example = "2020-03-20 01:54:12", description = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Hospital deletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Get deletedAt
   * @return deletedAt
  **/
  @Schema(example = "2020-03-20 01:54:12", description = "")
  public String getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Hospital hospital = (Hospital) o;
    return Objects.equals(this.id, hospital.id) &&
        Objects.equals(this.name, hospital.name) &&
        Objects.equals(this.nameSi, hospital.nameSi) &&
        Objects.equals(this.nameTa, hospital.nameTa) &&
        Objects.equals(this.createdAt, hospital.createdAt) &&
        Objects.equals(this.updatedAt, hospital.updatedAt) &&
        Objects.equals(this.deletedAt, hospital.deletedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, nameSi, nameTa, createdAt, updatedAt, deletedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Hospital {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameSi: ").append(toIndentedString(nameSi)).append("\n");
    sb.append("    nameTa: ").append(toIndentedString(nameTa)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
